### ISSUE TITLE
Tried this. Build fails on opam install dune reason

### ISSUE THREAD

**Issue by idkjs** [jaredly/reason-docker-server#1]
Fails here: `/bin/sh -c opam install dune reason`

Any obvious thing going here that you can see?

```s
PrisBook:rocker$ docker build --rm -f "Dockerfile" -t rocker:latest .
Sending build context to Docker daemon  3.072kB
Step 1/16 : FROM ocaml/opam:alpine as base
 ---> 5676a1ea7338
Step 2/16 : RUN sudo apk update
 ---> Using cache
 ---> 43d8abca760d
Step 3/16 : RUN sudo apk add m4
 ---> Using cache
 ---> 15df10602238
Step 4/16 : RUN sh -c "cd ~/opam-repository && git pull -q"
 ---> Using cache
 ---> 053021eeb9c0
Step 5/16 : RUN opam update
 ---> Using cache
 ---> 725e8b2a7c71
Step 6/16 : RUN opam install dune reason > /dev/null 2>&1
 ---> Running in 276b62ebe4ef
The command '/bin/sh -c opam install dune reason > /dev/null 2>&1' returned a non-zero code: 66
```

Thanks, brother. 

Namaste

**Comment by thomasmarcel** [comment]
Hey @idkjs, not sure if you're still stuck on this, I had the same problem, my solution was to switch the image to `ocaml/opam2:alpine` and add `RUN opam switch 4.06` after the apk commands (you can check my fork of this repo).

By removing the output redirections (`> /dev/null 2>&1`), you get more information about what's failing. The update was returning a bunch of errors because of the opam version, and then some other command was returning that the ocaml dependency didn't match.

**Comment by idkjs** [comment]
@ThomasMarcel, merci, brother.

I had identified the same problem but in fact never figured it out. Thanks for taking time to share tip on removing output redirection. Checking your fork...

**Comment by jimmyhuco** [comment]
Just change opam to opam2: `FROM ocaml/opam2:alpine as base`.
 And `RUN sh -c "cd ~/opam-repository && git pull -q"` is not necessary.
